# Change these first
owner: wtfpeter # Your GitHub username
repo: stats # Your Github repository name

# Add your sites here
sites:
  - name: Plex
    url: $PLEX
    __dangerous__insecure: true
  - name: Ombi
    url: https://ombi.pethor.eu/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.pethor.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  introTitle:
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
